fjcoding/AT13

- src/main/java/org/fundacionjala/at13/authenticator/Auth.java
Hi Team, there is the assignment for the Reviewers.
> Review requirements - Authenticate a list of usernames

- .github/workflows/gradle.yml
- build.gradle
- config/checkstyle/checkstyle.xml
- src/main/java/org/fundacionjala/at13/spaceinvaders/Alien.java
Add files needed to run checkstyle using gradle and include this as part of a GitHub workflow
> Automate checkstyle

- config/checkstyle/checkstyle.xml
- src/main/java/org/fundacionjala/at13/Main.java
Also, removed some checks due those are not going to be needed by this
project: javadocs, star import
> Fixed issues reported by checkstyle related to utility class and missing end of file

- src/main/java/org/fundacionjala/at13/students/RaymundoGuaraguara.java
Add space both before and after +, =.
Add functions description.
Change magic numbers for constants.
Add space before {.
Change method's name ShowNickname for showNickname.
> Fix checkstyle on RaymundoGuaraguara.java 

- src/main/java/org/fundacionjala/at13/students/JoelRojas.java
Add description comments to attributes and methods, delete and add blank space
> Automate checkstyle joel

- src/main/java/org/fundacionjala/at13/students/GustavoHuanca.java
Fix error in GustavoHuanca.java following the rule of checkstyle.
> Fix error with Checkstyle in GustavoHuanca.java

- src/main/java/org/fundacionjala/at13/students/JoelRojas.java
- src/main/java/org/fundacionjala/at13/students/RaymundoGuaraguara.java
- src/main/java/org/fundacionjala/at13/students/SaulCaspa.java
Fixed checkstyle errors in class SaulCaspa.java
> fixed checkstyle erros in class SaulCaspa.java

- src/main/java/org/fundacionjala/at13/students/PaolaAguilar.java
Deleting magic numbers.
Adding coments on methods.
Cleaning the code.
Improving code writting.
> Fixing errors from checkStyle of PaolaAguilar.java

- src/main/java/org/fundacionjala/at13/students/EdsonAnawayaRios.java
fix checkstyle archive EdsonAnawayaRios.java
> Fix checkstyles errors

- src/main/java/org/fundacionjala/at13/spaceinvaders/Alien.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/Matrix.java
Change data type from int to final int.
Add function description on all Alien and Matrix methods.
Add space before {.
Add space before and after =.
> Fix checkstyles errors in files Matrix.java and Alien.java

- src/main/java/org/fundacionjala/at13/spaceinvaders/Bullet.java
> Fix checkstyle Bullet.java

- src/main/java/org/fundacionjala/at13/Main.java
remove space before ).
add space before and after +.
> Fix checkstyle in Main.java

- .github/workflows/gradle.yml
- build.gradle
Add jacoco plugin for code coverage reports and include task to execute this report in GitHub workflow
> Jacoco test report

- src/main/java/org/fundacionjala/at13/spaceinvaders/Bullet.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/bulletTest.java
Modified methods name in class Bullet.java
Add Test for bulletTest.java
Test for positionX
Test for positionY
Test for colapsedBullet
And correct the other tests.
> Modified methods name and add test for Bullet.class

- src/test/java/org/fundacionjala/at13/spaceinvaders/MenuTest.java
Add test in method menuOption  about the option incorrect into file Menu.java
> add test in method menuOption 

- src/main/java/org/fundacionjala/at13/spaceinvaders/Spaceship.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/SpaceshipTest.java
Modified methods name in class SpaceshipTest.java
Add Test for:
setPosX
setPosY
getLowerLimint
getUpperLimint
Add additional Test for:
moveToRight
moveToLeft
> Fix jacoco spaceship

- src/main/java/org/fundacionjala/at13/spaceinvaders/AlienGroup.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/AlienGroupTest.java
Added class AlienGroup, a method to add aliens to an array, get an array, and unit tests for these methods.
> Class Alien Group add aliens

- src/main/java/org/fundacionjala/at13/spaceinvaders/Alien.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/AlienGroup.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/AlienGroupTest.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/AlienTest.java
Add tests of Alien Class, and AlienGroup
> Class alien group

- src/main/java/org/fundacionjala/at13/spaceinvaders/Bullet.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/Main.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/bulletTest.java
Fix and add methods in Bullet java
Improving methods to use for Alien and Spaceship class
Improve method bullet moving for Alien and Spaceship
Fix previos errors with limits in moving Bullet
Add test for each of the methods added, coverage of code at 100%, branches 80%
> Update, fix and add methods and test to Bullet.java and bulletTest

- src/main/java/org/fundacionjala/at13/spaceinvaders/Alien.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/Bullet.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/Main.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/Spaceship.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/AlienTest.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/SpaceshipTest.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/bulletTest.java
Change constructor in Bullet class.
Change calling constructor in Spaceship and Alien class.
- (Its needed to) Review the Tests class in Spaceship, Alien. Need to change the constructor.
> Modifying Bullet constructor in Bullet, Alien and Spaceship class

- src/main/java/org/fundacionjala/at13/spaceinvaders/Alien.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/AlienGroup.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/Main.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/Space.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/AlienGroupTest.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/AlienTest.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/SpaceTest.java
Files changed: Alien.java, AlienGroup.java, AlienTest.java, AliengroupTest.java, Space.java, SpaceTest.java and Main.java
> Change 7 files to integrate alienGroup

- src/test/java/org/fundacionjala/at13/spaceinvaders/bulletTest.java
> Add unitest

- src/main/java/org/fundacionjala/at13/spaceinvaders/Bullet.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/GameBoard.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/bulletTest.java
Refactor in the class bullet, now use variable bulletexist in class gameboard
> Interface refactor

- src/main/java/org/fundacionjala/at13/spaceinvaders/Bullet.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/GameBoard.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/bulletTest.java
For now only shoot the alien group
> added function so that the group of aliens can shoot

- src/main/java/org/fundacionjala/at13/spaceinvaders/Bullet.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/GameBoard.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/Main.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/bulletTest.java
Added function for aliens to take our lives and lost game message
> Interface space ship lives

- src/main/java/org/fundacionjala/at13/spaceinvaders/Bullet.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/GameBoard.java
- src/main/java/org/fundacionjala/at13/spaceinvaders/Main.java
- src/test/java/org/fundacionjala/at13/spaceinvaders/bulletTest.java
Added score function for spaceship and victory message
> Interface points

- src/main/java/org/fundacionjala/at13/spaceinvaders/GameBoard.java
Show game over interface when losing the game due to:
- Losing three lives
- AlienGroup reaching Spaceship
> Show GameOver interface from GameBoard
